services:
  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
      target: php-fpm
    expose:
      - "9000"
    volumes:
      - ./projects:/var/www/projects
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgresql:
    driver: local
